#tomcat configurations
server:
  port: 5000
  error:
    # to exclude stack trace in custom exception messages
    include-stacktrace: never

spring:
#  h2:
#    console:
#      enabled: true
#      settings.web-allow-others: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
  # configuring basename here instead of @Bean config for ResourceBundleMessageSource
  messages:
    basename: messages
  # by default the username will be "user" and password will be generated and printed in console
  security:
    user:
      name: username
      password: password

  # to connect to RDS / local by default
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_PORT:3306}/${RDS_DB_NAME:coursedb}
    username: ${RDS_USERNAME:course_user}
    password: ${RDS_PASSWORD:dummypassword}


#spring boot actuator configurations
management:
  endpoint:
    shutdown:
      enabled: true
  server:
    port: 5000
  endpoints:
    web:
      exposure:
        include: "*"